//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healkeep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserComments
    {
        public long AspNetUserCommentID { get; set; }
        public Nullable<bool> CheckedUp { get; set; }
        public string AspNetUserID { get; set; }
        public Nullable<long> CommentID { get; set; }
        public Nullable<long> NaturalTreatmentID { get; set; }
        public Nullable<bool> CheckedDown { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Comments Comments { get; set; }
        public virtual NaturalTreatments NaturalTreatments { get; set; }
    }
}
