//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healkeep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comments()
        {
            this.AspNetUserComments = new HashSet<AspNetUserComments>();
            this.Comments1 = new HashSet<Comments>();
        }
    
        public long CommentID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string AspNetUserID { get; set; }
        public long NaturalTreatmentID { get; set; }
        public Nullable<long> CommentCommentID { get; set; }
        public int VoteUp { get; set; }
        public int VoteDown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserComments> AspNetUserComments { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual Comments Comments2 { get; set; }
        public virtual NaturalTreatments NaturalTreatments { get; set; }
    }
}
