//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healkeep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaturalTreatments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NaturalTreatments()
        {
            this.AspNetUserComments = new HashSet<AspNetUserComments>();
            this.Comments = new HashSet<Comments>();
        }
    
        public long NaturalTreatmentID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ScoreUsers { get; set; }
        public Nullable<decimal> ScoreEntities { get; set; }
        public string Description { get; set; }
        public long DiseaseID { get; set; }
        public bool Treatment { get; set; }
        public bool Prevention { get; set; }
        public bool Approved { get; set; }
        public string AspNetUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserComments> AspNetUserComments { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Diseases Diseases { get; set; }
    }
}
